build_linux_appimage:
  stage: build
  image: python:${PYTHON_VERSION}-buster
  before_script:
    # Install dependencies
    - apt-get update && apt-get install -y fuse libfuse2
    - pip install pyinstaller
    - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
    - chmod +x appimagetool-x86_64.AppImage
  script:
    # Prepare AppDir structure
    - mkdir -p AppDir/usr/bin AppDir/usr/share/applications AppDir/usr/share/icons/hicolor/256x256/apps
    
    # Build the application (replace 'installer_gui.py' with the correct filename if different)
    - pyinstaller --onefile --windowed your_actual_script_name.py
    - mv dist/your_actual_script_name AppDir/usr/bin/
    
    # Create desktop entry file
    - |
      cat << EOF > AppDir/usr/share/applications/your_app_name.desktop
      [Desktop Entry]
      Name=Your App Name
      Exec=your_actual_script_name
      Icon=your_app_icon
      Type=Application
      Categories=Utility;
      EOF
    
    # Create AppImage
    - ./appimagetool-x86_64.AppImage AppDir
  artifacts:
    paths:
      - ${APPIMAGE_NAME}
