build_linux_appimage:
  stage: build
  image: python:${PYTHON_VERSION}-buster
  before_script:
    # Install dependencies
    - apt-get update && apt-get install -y fuse libfuse2
    - pip install pyinstaller
    - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
    - chmod +x appimagetool-x86_64.AppImage
  script:
    # Prepare AppDir structure
    - mkdir -p AppDir/usr/bin AppDir/usr/share/applications AppDir/usr/share/icons/hicolor/256x256/apps
    
    # Build the application
    - pyinstaller --onefile --windowed installer_gui.py
    - mv dist/installer_gui AppDir/usr/bin/
    
    # Create desktop entry file
    - |
      cat << EOF > AppDir/usr/share/applications/installer-gui.desktop
      [Desktop Entry]
      Name=Installer GUI
      Exec=installer_gui
      Icon=system-software-install
      Type=Application
      Categories=Utility;
      EOF
    
    # Create AppImage
    - ./appimagetool-x86_64.AppImage AppDir
    - mv *.AppImage ${APPIMAGE_NAME}
  artifacts:
    paths:
      - ${APPIMAGE_NAME}